#pragma once

#include <ui/keyboard.hpp>
#include <SDL2/SDL_keyboard.h>

namespace ui::sdl
{
	constexpr modifiers from_sdl(SDL_Keymod key) noexcept
	{
		// modifier values exactly match SDL values
		return modifiers(key);
	}

	constexpr SDL_Keymod to_sdl(modifiers key) noexcept
	{
		// modifier values exactly match SDL values
		return SDL_Keymod(key);
	}

	constexpr keys from_sdl(SDL_Keycode value) noexcept
	{
		return value == SDLK_RETURN ? keys::enter
			: value == SDLK_ESCAPE ? keys::escape
			: value == SDLK_BACKSPACE ? keys::backspace
			: value == SDLK_TAB ? keys::tab
			: value == SDLK_SPACE ? keys::space
			: value == SDLK_EXCLAIM ? keys::exclaim
			: value == SDLK_QUOTEDBL ? keys::quotedbl
			: value == SDLK_HASH ? keys::hash
			: value == SDLK_PERCENT ? keys::percent
			: value == SDLK_DOLLAR ? keys::dollar
			: value == SDLK_AMPERSAND ? keys::ampersand
			: value == SDLK_QUOTE ? keys::quote
			: value == SDLK_LEFTPAREN ? keys::left_paren
			: value == SDLK_RIGHTPAREN ? keys::right_paren
			: value == SDLK_ASTERISK ? keys::asterisk
			: value == SDLK_PLUS ? keys::plus
			: value == SDLK_COMMA ? keys::comma
			: value == SDLK_MINUS ? keys::minus
			: value == SDLK_PERIOD ? keys::period
			: value == SDLK_SLASH ? keys::slash
			: value == SDLK_0 ? keys::num_0
			: value == SDLK_1 ? keys::num_1
			: value == SDLK_2 ? keys::num_2
			: value == SDLK_3 ? keys::num_3
			: value == SDLK_4 ? keys::num_4
			: value == SDLK_5 ? keys::num_5
			: value == SDLK_6 ? keys::num_6
			: value == SDLK_7 ? keys::num_7
			: value == SDLK_8 ? keys::num_8
			: value == SDLK_9 ? keys::num_9
			: value == SDLK_COLON ? keys::colon
			: value == SDLK_SEMICOLON ? keys::semicolon
			: value == SDLK_LESS ? keys::less
			: value == SDLK_EQUALS ? keys::equals
			: value == SDLK_GREATER ? keys::greater
			: value == SDLK_QUESTION ? keys::question
			: value == SDLK_AT ? keys::at
			: value == SDLK_LEFTBRACKET ? keys::left_bracket
			: value == SDLK_BACKSLASH ? keys::backslash
			: value == SDLK_RIGHTBRACKET ? keys::right_bracket
			: value == SDLK_CARET ? keys::caret
			: value == SDLK_UNDERSCORE ? keys::underscore
			: value == SDLK_BACKQUOTE ? keys::backquote
			: value == SDLK_a ? keys::a
			: value == SDLK_b ? keys::b
			: value == SDLK_c ? keys::c
			: value == SDLK_d ? keys::d
			: value == SDLK_e ? keys::e
			: value == SDLK_f ? keys::f
			: value == SDLK_g ? keys::g
			: value == SDLK_h ? keys::h
			: value == SDLK_i ? keys::i
			: value == SDLK_j ? keys::j
			: value == SDLK_k ? keys::k
			: value == SDLK_l ? keys::l
			: value == SDLK_m ? keys::m
			: value == SDLK_n ? keys::n
			: value == SDLK_o ? keys::o
			: value == SDLK_p ? keys::p
			: value == SDLK_q ? keys::q
			: value == SDLK_r ? keys::r
			: value == SDLK_s ? keys::s
			: value == SDLK_t ? keys::t
			: value == SDLK_u ? keys::u
			: value == SDLK_v ? keys::v
			: value == SDLK_w ? keys::w
			: value == SDLK_x ? keys::x
			: value == SDLK_y ? keys::y
			: value == SDLK_z ? keys::z
			: value == SDLK_CAPSLOCK ? keys::capslock
			: value == SDLK_F1 ? keys::f1
			: value == SDLK_F2 ? keys::f2
			: value == SDLK_F3 ? keys::f3
			: value == SDLK_F4 ? keys::f4
			: value == SDLK_F5 ? keys::f5
			: value == SDLK_F6 ? keys::f6
			: value == SDLK_F7 ? keys::f7
			: value == SDLK_F8 ? keys::f8
			: value == SDLK_F9 ? keys::f9
			: value == SDLK_F10 ? keys::f10
			: value == SDLK_F11 ? keys::f11
			: value == SDLK_F12 ? keys::f12
			: value == SDLK_PRINTSCREEN ? keys::printscreen
			: value == SDLK_SCROLLLOCK ? keys::scroll_lock
			: value == SDLK_PAUSE ? keys::pause
			: value == SDLK_INSERT ? keys::insert
			: value == SDLK_HOME ? keys::home
			: value == SDLK_PAGEUP ? keys::page_up
			: value == SDLK_DELETE ? keys::del
			: value == SDLK_END ? keys::end
			: value == SDLK_PAGEDOWN ? keys::page_down
			: value == SDLK_RIGHT ? keys::right
			: value == SDLK_LEFT ? keys::left
			: value == SDLK_DOWN ? keys::down
			: value == SDLK_UP ? keys::up
			: value == SDLK_NUMLOCKCLEAR ? keys::numlock_clear
			: value == SDLK_KP_DIVIDE ? keys::kp_divide
			: value == SDLK_KP_MULTIPLY ? keys::kp_multiply
			: value == SDLK_KP_MINUS ? keys::kp_minus
			: value == SDLK_KP_PLUS ? keys::kp_plus
			: value == SDLK_KP_ENTER ? keys::kp_enter
			: value == SDLK_KP_1 ? keys::kp_1
			: value == SDLK_KP_2 ? keys::kp_2
			: value == SDLK_KP_3 ? keys::kp_3
			: value == SDLK_KP_4 ? keys::kp_4
			: value == SDLK_KP_5 ? keys::kp_5
			: value == SDLK_KP_6 ? keys::kp_6
			: value == SDLK_KP_7 ? keys::kp_7
			: value == SDLK_KP_8 ? keys::kp_8
			: value == SDLK_KP_9 ? keys::kp_9
			: value == SDLK_KP_0 ? keys::kp_0
			: value == SDLK_KP_PERIOD ? keys::kp_period
			: value == SDLK_APPLICATION ? keys::application
			: value == SDLK_POWER ? keys::power
			: value == SDLK_KP_EQUALS ? keys::kp_equals
			: value == SDLK_F13 ? keys::f13
			: value == SDLK_F14 ? keys::f14
			: value == SDLK_F15 ? keys::f15
			: value == SDLK_F16 ? keys::f16
			: value == SDLK_F17 ? keys::f17
			: value == SDLK_F18 ? keys::f18
			: value == SDLK_F19 ? keys::f19
			: value == SDLK_F20 ? keys::f20
			: value == SDLK_F21 ? keys::f21
			: value == SDLK_F22 ? keys::f22
			: value == SDLK_F23 ? keys::f23
			: value == SDLK_F24 ? keys::f24
			: value == SDLK_EXECUTE ? keys::execute
			: value == SDLK_HELP ? keys::help
			: value == SDLK_MENU ? keys::menu
			: value == SDLK_SELECT ? keys::select
			: value == SDLK_STOP ? keys::stop
			: value == SDLK_AGAIN ? keys::again
			: value == SDLK_UNDO ? keys::undo
			: value == SDLK_CUT ? keys::cut
			: value == SDLK_COPY ? keys::copy
			: value == SDLK_PASTE ? keys::paste
			: value == SDLK_FIND ? keys::find
			: value == SDLK_MUTE ? keys::mute
			: value == SDLK_VOLUMEUP ? keys::volume_up
			: value == SDLK_VOLUMEDOWN ? keys::volume_down
			: value == SDLK_KP_COMMA ? keys::kp_comma
			: value == SDLK_KP_EQUALSAS400 ? keys::kp_equalsas400
			: value == SDLK_ALTERASE ? keys::alterase
			: value == SDLK_SYSREQ ? keys::sysreq
			: value == SDLK_CANCEL ? keys::cancel
			: value == SDLK_CLEAR ? keys::clear
			: value == SDLK_PRIOR ? keys::prior
			: value == SDLK_RETURN2 ? keys::return2
			: value == SDLK_SEPARATOR ? keys::separator
			: value == SDLK_OUT ? keys::out
			: value == SDLK_OPER ? keys::oper
			: value == SDLK_CLEARAGAIN ? keys::clear_again
			: value == SDLK_CRSEL ? keys::crsel
			: value == SDLK_EXSEL ? keys::exsel
			: value == SDLK_KP_00 ? keys::kp_00
			: value == SDLK_KP_000 ? keys::kp_000
			: value == SDLK_THOUSANDSSEPARATOR ? keys::thousands_separator
			: value == SDLK_DECIMALSEPARATOR ? keys::decimal_separator
			: value == SDLK_CURRENCYUNIT ? keys::currency_unit
			: value == SDLK_CURRENCYSUBUNIT ? keys::currency_subunit
			: value == SDLK_KP_LEFTPAREN ? keys::kp_left_paren
			: value == SDLK_KP_RIGHTPAREN ? keys::kp_right_paren
			: value == SDLK_KP_LEFTBRACE ? keys::kp_left_brace
			: value == SDLK_KP_RIGHTBRACE ? keys::kp_right_brace
			: value == SDLK_KP_TAB ? keys::kp_tab
			: value == SDLK_KP_BACKSPACE ? keys::kp_backspace
			: value == SDLK_KP_A ? keys::kp_a
			: value == SDLK_KP_B ? keys::kp_b
			: value == SDLK_KP_C ? keys::kp_c
			: value == SDLK_KP_D ? keys::kp_d
			: value == SDLK_KP_E ? keys::kp_e
			: value == SDLK_KP_F ? keys::kp_f
			: value == SDLK_KP_XOR ? keys::kp_xor
			: value == SDLK_KP_POWER ? keys::kp_power
			: value == SDLK_KP_PERCENT ? keys::kp_percent
			: value == SDLK_KP_LESS ? keys::kp_less
			: value == SDLK_KP_GREATER ? keys::kp_greater
			: value == SDLK_KP_AMPERSAND ? keys::kp_ampersand
			: value == SDLK_KP_DBLAMPERSAND ? keys::kp_dblampersand
			: value == SDLK_KP_VERTICALBAR ? keys::kp_verticalbar
			: value == SDLK_KP_DBLVERTICALBAR ? keys::kp_dblverticalbar
			: value == SDLK_KP_COLON ? keys::kp_colon
			: value == SDLK_KP_HASH ? keys::kp_hash
			: value == SDLK_KP_SPACE ? keys::kp_space
			: value == SDLK_KP_AT ? keys::kp_at
			: value == SDLK_KP_EXCLAM ? keys::kp_exclam
			: value == SDLK_KP_MEMSTORE ? keys::kp_mem_store
			: value == SDLK_KP_MEMRECALL ? keys::kp_mem_recall
			: value == SDLK_KP_MEMCLEAR ? keys::kp_mem_clear
			: value == SDLK_KP_MEMADD ? keys::kp_mem_add
			: value == SDLK_KP_MEMSUBTRACT ? keys::kp_mem_subtract
			: value == SDLK_KP_MEMMULTIPLY ? keys::kp_mem_multiply
			: value == SDLK_KP_MEMDIVIDE ? keys::kp_mem_divide
			: value == SDLK_KP_PLUSMINUS ? keys::kp_plus_minus
			: value == SDLK_KP_CLEAR ? keys::kp_clear
			: value == SDLK_KP_CLEARENTRY ? keys::kp_clear_entry
			: value == SDLK_KP_BINARY ? keys::kp_binary
			: value == SDLK_KP_OCTAL ? keys::kp_octal
			: value == SDLK_KP_DECIMAL ? keys::kp_decimal
			: value == SDLK_KP_HEXADECIMAL ? keys::kp_hexadecimal
			: value == SDLK_LCTRL ? keys::left_ctrl
			: value == SDLK_LSHIFT ? keys::left_shift
			: value == SDLK_LALT ? keys::left_alt
			: value == SDLK_LGUI ? keys::left_gui
			: value == SDLK_RCTRL ? keys::right_ctrl
			: value == SDLK_RSHIFT ? keys::right_shift
			: value == SDLK_RALT ? keys::right_alt
			: value == SDLK_RGUI ? keys::right_gui
			: value == SDLK_MODE ? keys::mode
			: value == SDLK_AUDIONEXT ? keys::audio_next
			: value == SDLK_AUDIOPREV ? keys::audio_prev
			: value == SDLK_AUDIOSTOP ? keys::audio_stop
			: value == SDLK_AUDIOPLAY ? keys::audio_play
			: value == SDLK_AUDIOMUTE ? keys::audio_mute
			: value == SDLK_MEDIASELECT ? keys::media_select
			: value == SDLK_WWW ? keys::www
			: value == SDLK_MAIL ? keys::mail
			: value == SDLK_CALCULATOR ? keys::calculator
			: value == SDLK_COMPUTER ? keys::computer
			: value == SDLK_AC_SEARCH ? keys::ac_search
			: value == SDLK_AC_HOME ? keys::ac_home
			: value == SDLK_AC_BACK ? keys::ac_back
			: value == SDLK_AC_FORWARD ? keys::ac_forward
			: value == SDLK_AC_STOP ? keys::ac_stop
			: value == SDLK_AC_REFRESH ? keys::ac_refresh
			: value == SDLK_AC_BOOKMARKS ? keys::ac_bookmarks
			: value == SDLK_BRIGHTNESSDOWN ? keys::brightness_down
			: value == SDLK_BRIGHTNESSUP ? keys::brightness_up
			: value == SDLK_DISPLAYSWITCH ? keys::display_switch
			: value == SDLK_KBDILLUMTOGGLE ? keys::kbd_illum_toggle
			: value == SDLK_KBDILLUMDOWN ? keys::kbd_illum_down
			: value == SDLK_KBDILLUMUP ? keys::kbd_illum_up
			: value == SDLK_EJECT ? keys::eject
			: value == SDLK_SLEEP ? keys::sleep
			: value == SDLK_APP1 ? keys::app1
			: value == SDLK_APP2 ? keys::app2
			: value == SDLK_AUDIOREWIND ? keys::audio_rewind
			: value == SDLK_AUDIOFASTFORWARD ? keys::audio_fast_forward
			: keys::unknown;
	}

	constexpr SDL_Keycode to_sdl(keys value) noexcept
	{
		return value == keys::enter ? SDLK_RETURN
			: value == keys::escape ? SDLK_ESCAPE
			: value == keys::backspace ? SDLK_BACKSPACE
			: value == keys::tab ? SDLK_TAB
			: value == keys::space ? SDLK_SPACE
			: value == keys::exclaim ? SDLK_EXCLAIM
			: value == keys::quotedbl ? SDLK_QUOTEDBL
			: value == keys::hash ? SDLK_HASH
			: value == keys::percent ? SDLK_PERCENT
			: value == keys::dollar ? SDLK_DOLLAR
			: value == keys::ampersand ? SDLK_AMPERSAND
			: value == keys::quote ? SDLK_QUOTE
			: value == keys::left_paren ? SDLK_LEFTPAREN
			: value == keys::right_paren ? SDLK_RIGHTPAREN
			: value == keys::asterisk ? SDLK_ASTERISK
			: value == keys::plus ? SDLK_PLUS
			: value == keys::comma ? SDLK_COMMA
			: value == keys::minus ? SDLK_MINUS
			: value == keys::period ? SDLK_PERIOD
			: value == keys::slash ? SDLK_SLASH
			: value == keys::num_0 ? SDLK_0
			: value == keys::num_1 ? SDLK_1
			: value == keys::num_2 ? SDLK_2
			: value == keys::num_3 ? SDLK_3
			: value == keys::num_4 ? SDLK_4
			: value == keys::num_5 ? SDLK_5
			: value == keys::num_6 ? SDLK_6
			: value == keys::num_7 ? SDLK_7
			: value == keys::num_8 ? SDLK_8
			: value == keys::num_9 ? SDLK_9
			: value == keys::colon ? SDLK_COLON
			: value == keys::semicolon ? SDLK_SEMICOLON
			: value == keys::less ? SDLK_LESS
			: value == keys::equals ? SDLK_EQUALS
			: value == keys::greater ? SDLK_GREATER
			: value == keys::question ? SDLK_QUESTION
			: value == keys::at ? SDLK_AT
			: value == keys::left_bracket ? SDLK_LEFTBRACKET
			: value == keys::backslash ? SDLK_BACKSLASH
			: value == keys::right_bracket ? SDLK_RIGHTBRACKET
			: value == keys::caret ? SDLK_CARET
			: value == keys::underscore ? SDLK_UNDERSCORE
			: value == keys::backquote ? SDLK_BACKQUOTE
			: value == keys::a ? SDLK_a
			: value == keys::b ? SDLK_b
			: value == keys::c ? SDLK_c
			: value == keys::d ? SDLK_d
			: value == keys::e ? SDLK_e
			: value == keys::f ? SDLK_f
			: value == keys::g ? SDLK_g
			: value == keys::h ? SDLK_h
			: value == keys::i ? SDLK_i
			: value == keys::j ? SDLK_j
			: value == keys::k ? SDLK_k
			: value == keys::l ? SDLK_l
			: value == keys::m ? SDLK_m
			: value == keys::n ? SDLK_n
			: value == keys::o ? SDLK_o
			: value == keys::p ? SDLK_p
			: value == keys::q ? SDLK_q
			: value == keys::r ? SDLK_r
			: value == keys::s ? SDLK_s
			: value == keys::t ? SDLK_t
			: value == keys::u ? SDLK_u
			: value == keys::v ? SDLK_v
			: value == keys::w ? SDLK_w
			: value == keys::x ? SDLK_x
			: value == keys::y ? SDLK_y
			: value == keys::z ? SDLK_z
			: value == keys::capslock ? SDLK_CAPSLOCK
			: value == keys::f1 ? SDLK_F1
			: value == keys::f2 ? SDLK_F2
			: value == keys::f3 ? SDLK_F3
			: value == keys::f4 ? SDLK_F4
			: value == keys::f5 ? SDLK_F5
			: value == keys::f6 ? SDLK_F6
			: value == keys::f7 ? SDLK_F7
			: value == keys::f8 ? SDLK_F8
			: value == keys::f9 ? SDLK_F9
			: value == keys::f10 ? SDLK_F10
			: value == keys::f11 ? SDLK_F11
			: value == keys::f12 ? SDLK_F12
			: value == keys::printscreen ? SDLK_PRINTSCREEN
			: value == keys::scroll_lock ? SDLK_SCROLLLOCK
			: value == keys::pause ? SDLK_PAUSE
			: value == keys::insert ? SDLK_INSERT
			: value == keys::home ? SDLK_HOME
			: value == keys::page_up ? SDLK_PAGEUP
			: value == keys::del ? SDLK_DELETE
			: value == keys::end ? SDLK_END
			: value == keys::page_down ? SDLK_PAGEDOWN
			: value == keys::right ? SDLK_RIGHT
			: value == keys::left ? SDLK_LEFT
			: value == keys::down ? SDLK_DOWN
			: value == keys::up ? SDLK_UP
			: value == keys::numlock_clear ? SDLK_NUMLOCKCLEAR
			: value == keys::kp_divide ? SDLK_KP_DIVIDE
			: value == keys::kp_multiply ? SDLK_KP_MULTIPLY
			: value == keys::kp_minus ? SDLK_KP_MINUS
			: value == keys::kp_plus ? SDLK_KP_PLUS
			: value == keys::kp_enter ? SDLK_KP_ENTER
			: value == keys::kp_1 ? SDLK_KP_1
			: value == keys::kp_2 ? SDLK_KP_2
			: value == keys::kp_3 ? SDLK_KP_3
			: value == keys::kp_4 ? SDLK_KP_4
			: value == keys::kp_5 ? SDLK_KP_5
			: value == keys::kp_6 ? SDLK_KP_6
			: value == keys::kp_7 ? SDLK_KP_7
			: value == keys::kp_8 ? SDLK_KP_8
			: value == keys::kp_9 ? SDLK_KP_9
			: value == keys::kp_0 ? SDLK_KP_0
			: value == keys::kp_period ? SDLK_KP_PERIOD
			: value == keys::application ? SDLK_APPLICATION
			: value == keys::power ? SDLK_POWER
			: value == keys::kp_equals ? SDLK_KP_EQUALS
			: value == keys::f13 ? SDLK_F13
			: value == keys::f14 ? SDLK_F14
			: value == keys::f15 ? SDLK_F15
			: value == keys::f16 ? SDLK_F16
			: value == keys::f17 ? SDLK_F17
			: value == keys::f18 ? SDLK_F18
			: value == keys::f19 ? SDLK_F19
			: value == keys::f20 ? SDLK_F20
			: value == keys::f21 ? SDLK_F21
			: value == keys::f22 ? SDLK_F22
			: value == keys::f23 ? SDLK_F23
			: value == keys::f24 ? SDLK_F24
			: value == keys::execute ? SDLK_EXECUTE
			: value == keys::help ? SDLK_HELP
			: value == keys::menu ? SDLK_MENU
			: value == keys::select ? SDLK_SELECT
			: value == keys::stop ? SDLK_STOP
			: value == keys::again ? SDLK_AGAIN
			: value == keys::undo ? SDLK_UNDO
			: value == keys::cut ? SDLK_CUT
			: value == keys::copy ? SDLK_COPY
			: value == keys::paste ? SDLK_PASTE
			: value == keys::find ? SDLK_FIND
			: value == keys::mute ? SDLK_MUTE
			: value == keys::volume_up ? SDLK_VOLUMEUP
			: value == keys::volume_down ? SDLK_VOLUMEDOWN
			: value == keys::kp_comma ? SDLK_KP_COMMA
			: value == keys::kp_equalsas400 ? SDLK_KP_EQUALSAS400
			: value == keys::alterase ? SDLK_ALTERASE
			: value == keys::sysreq ? SDLK_SYSREQ
			: value == keys::cancel ? SDLK_CANCEL
			: value == keys::clear ? SDLK_CLEAR
			: value == keys::prior ? SDLK_PRIOR
			: value == keys::return2 ? SDLK_RETURN2
			: value == keys::separator ? SDLK_SEPARATOR
			: value == keys::out ? SDLK_OUT
			: value == keys::oper ? SDLK_OPER
			: value == keys::clear_again ? SDLK_CLEARAGAIN
			: value == keys::crsel ? SDLK_CRSEL
			: value == keys::exsel ? SDLK_EXSEL
			: value == keys::kp_00 ? SDLK_KP_00
			: value == keys::kp_000 ? SDLK_KP_000
			: value == keys::thousands_separator ? SDLK_THOUSANDSSEPARATOR
			: value == keys::decimal_separator ? SDLK_DECIMALSEPARATOR
			: value == keys::currency_unit ? SDLK_CURRENCYUNIT
			: value == keys::currency_subunit ? SDLK_CURRENCYSUBUNIT
			: value == keys::kp_left_paren ? SDLK_KP_LEFTPAREN
			: value == keys::kp_right_paren ? SDLK_KP_RIGHTPAREN
			: value == keys::kp_left_brace ? SDLK_KP_LEFTBRACE
			: value == keys::kp_right_brace ? SDLK_KP_RIGHTBRACE
			: value == keys::kp_tab ? SDLK_KP_TAB
			: value == keys::kp_backspace ? SDLK_KP_BACKSPACE
			: value == keys::kp_a ? SDLK_KP_A
			: value == keys::kp_b ? SDLK_KP_B
			: value == keys::kp_c ? SDLK_KP_C
			: value == keys::kp_d ? SDLK_KP_D
			: value == keys::kp_e ? SDLK_KP_E
			: value == keys::kp_f ? SDLK_KP_F
			: value == keys::kp_xor ? SDLK_KP_XOR
			: value == keys::kp_power ? SDLK_KP_POWER
			: value == keys::kp_percent ? SDLK_KP_PERCENT
			: value == keys::kp_less ? SDLK_KP_LESS
			: value == keys::kp_greater ? SDLK_KP_GREATER
			: value == keys::kp_ampersand ? SDLK_KP_AMPERSAND
			: value == keys::kp_dblampersand ? SDLK_KP_DBLAMPERSAND
			: value == keys::kp_verticalbar ? SDLK_KP_VERTICALBAR
			: value == keys::kp_dblverticalbar ? SDLK_KP_DBLVERTICALBAR
			: value == keys::kp_colon ? SDLK_KP_COLON
			: value == keys::kp_hash ? SDLK_KP_HASH
			: value == keys::kp_space ? SDLK_KP_SPACE
			: value == keys::kp_at ? SDLK_KP_AT
			: value == keys::kp_exclam ? SDLK_KP_EXCLAM
			: value == keys::kp_mem_store ? SDLK_KP_MEMSTORE
			: value == keys::kp_mem_recall ? SDLK_KP_MEMRECALL
			: value == keys::kp_mem_clear ? SDLK_KP_MEMCLEAR
			: value == keys::kp_mem_add ? SDLK_KP_MEMADD
			: value == keys::kp_mem_subtract ? SDLK_KP_MEMSUBTRACT
			: value == keys::kp_mem_multiply ? SDLK_KP_MEMMULTIPLY
			: value == keys::kp_mem_divide ? SDLK_KP_MEMDIVIDE
			: value == keys::kp_plus_minus ? SDLK_KP_PLUSMINUS
			: value == keys::kp_clear ? SDLK_KP_CLEAR
			: value == keys::kp_clear_entry ? SDLK_KP_CLEARENTRY
			: value == keys::kp_binary ? SDLK_KP_BINARY
			: value == keys::kp_octal ? SDLK_KP_OCTAL
			: value == keys::kp_decimal ? SDLK_KP_DECIMAL
			: value == keys::kp_hexadecimal ? SDLK_KP_HEXADECIMAL
			: value == keys::left_ctrl ? SDLK_LCTRL
			: value == keys::left_shift ? SDLK_LSHIFT
			: value == keys::left_alt ? SDLK_LALT
			: value == keys::left_gui ? SDLK_LGUI
			: value == keys::right_ctrl ? SDLK_RCTRL
			: value == keys::right_shift ? SDLK_RSHIFT
			: value == keys::right_alt ? SDLK_RALT
			: value == keys::right_gui ? SDLK_RGUI
			: value == keys::mode ? SDLK_MODE
			: value == keys::audio_next ? SDLK_AUDIONEXT
			: value == keys::audio_prev ? SDLK_AUDIOPREV
			: value == keys::audio_stop ? SDLK_AUDIOSTOP
			: value == keys::audio_play ? SDLK_AUDIOPLAY
			: value == keys::audio_mute ? SDLK_AUDIOMUTE
			: value == keys::media_select ? SDLK_MEDIASELECT
			: value == keys::www ? SDLK_WWW
			: value == keys::mail ? SDLK_MAIL
			: value == keys::calculator ? SDLK_CALCULATOR
			: value == keys::computer ? SDLK_COMPUTER
			: value == keys::ac_search ? SDLK_AC_SEARCH
			: value == keys::ac_home ? SDLK_AC_HOME
			: value == keys::ac_back ? SDLK_AC_BACK
			: value == keys::ac_forward ? SDLK_AC_FORWARD
			: value == keys::ac_stop ? SDLK_AC_STOP
			: value == keys::ac_refresh ? SDLK_AC_REFRESH
			: value == keys::ac_bookmarks ? SDLK_AC_BOOKMARKS
			: value == keys::brightness_down ? SDLK_BRIGHTNESSDOWN
			: value == keys::brightness_up ? SDLK_BRIGHTNESSUP
			: value == keys::display_switch ? SDLK_DISPLAYSWITCH
			: value == keys::kbd_illum_toggle ? SDLK_KBDILLUMTOGGLE
			: value == keys::kbd_illum_down ? SDLK_KBDILLUMDOWN
			: value == keys::kbd_illum_up ? SDLK_KBDILLUMUP
			: value == keys::eject ? SDLK_EJECT
			: value == keys::sleep ? SDLK_SLEEP
			: value == keys::app1 ? SDLK_APP1
			: value == keys::app2 ? SDLK_APP2
			: value == keys::audio_rewind ? SDLK_AUDIOREWIND
			: value == keys::audio_fast_forward ? SDLK_AUDIOFASTFORWARD
			: SDLK_UNKNOWN;
	}

	constexpr scancodes from_sdl(SDL_Scancode code) noexcept
	{
		return code == SDL_SCANCODE_A ? scancodes::a
			: code == SDL_SCANCODE_B ? scancodes::b
			: code == SDL_SCANCODE_C ? scancodes::c
			: code == SDL_SCANCODE_D ? scancodes::d
			: code == SDL_SCANCODE_E ? scancodes::e
			: code == SDL_SCANCODE_F ? scancodes::f
			: code == SDL_SCANCODE_G ? scancodes::g
			: code == SDL_SCANCODE_H ? scancodes::h
			: code == SDL_SCANCODE_I ? scancodes::i
			: code == SDL_SCANCODE_J ? scancodes::j
			: code == SDL_SCANCODE_K ? scancodes::k
			: code == SDL_SCANCODE_L ? scancodes::l
			: code == SDL_SCANCODE_M ? scancodes::m
			: code == SDL_SCANCODE_N ? scancodes::n
			: code == SDL_SCANCODE_O ? scancodes::o
			: code == SDL_SCANCODE_P ? scancodes::p
			: code == SDL_SCANCODE_Q ? scancodes::q
			: code == SDL_SCANCODE_R ? scancodes::r
			: code == SDL_SCANCODE_S ? scancodes::s
			: code == SDL_SCANCODE_T ? scancodes::t
			: code == SDL_SCANCODE_U ? scancodes::u
			: code == SDL_SCANCODE_V ? scancodes::v
			: code == SDL_SCANCODE_W ? scancodes::w
			: code == SDL_SCANCODE_X ? scancodes::x
			: code == SDL_SCANCODE_Y ? scancodes::y
			: code == SDL_SCANCODE_Z ? scancodes::z
			: code == SDL_SCANCODE_1 ? scancodes::num_1
			: code == SDL_SCANCODE_2 ? scancodes::num_2
			: code == SDL_SCANCODE_3 ? scancodes::num_3
			: code == SDL_SCANCODE_4 ? scancodes::num_4
			: code == SDL_SCANCODE_5 ? scancodes::num_5
			: code == SDL_SCANCODE_6 ? scancodes::num_6
			: code == SDL_SCANCODE_7 ? scancodes::num_7
			: code == SDL_SCANCODE_8 ? scancodes::num_8
			: code == SDL_SCANCODE_9 ? scancodes::num_9
			: code == SDL_SCANCODE_0 ? scancodes::num_0
			: code == SDL_SCANCODE_RETURN ? scancodes::enter
			: code == SDL_SCANCODE_ESCAPE ? scancodes::escape
			: code == SDL_SCANCODE_BACKSPACE ? scancodes::backspace
			: code == SDL_SCANCODE_TAB ? scancodes::tab
			: code == SDL_SCANCODE_SPACE ? scancodes::space
			: code == SDL_SCANCODE_MINUS ? scancodes::minus
			: code == SDL_SCANCODE_EQUALS ? scancodes::equals
			: code == SDL_SCANCODE_LEFTBRACKET ? scancodes::left_bracket
			: code == SDL_SCANCODE_RIGHTBRACKET ? scancodes::right_bracket
			: code == SDL_SCANCODE_BACKSLASH ? scancodes::backslash
			: code == SDL_SCANCODE_NONUSHASH ? scancodes::non_ushash
			: code == SDL_SCANCODE_SEMICOLON ? scancodes::semicolon
			: code == SDL_SCANCODE_APOSTROPHE ? scancodes::apostrophe
			: code == SDL_SCANCODE_GRAVE ? scancodes::grave
			: code == SDL_SCANCODE_COMMA ? scancodes::comma
			: code == SDL_SCANCODE_PERIOD ? scancodes::period
			: code == SDL_SCANCODE_SLASH ? scancodes::slash
			: code == SDL_SCANCODE_CAPSLOCK ? scancodes::capslock
			: code == SDL_SCANCODE_F1 ? scancodes::f1
			: code == SDL_SCANCODE_F2 ? scancodes::f2
			: code == SDL_SCANCODE_F3 ? scancodes::f3
			: code == SDL_SCANCODE_F4 ? scancodes::f4
			: code == SDL_SCANCODE_F5 ? scancodes::f5
			: code == SDL_SCANCODE_F6 ? scancodes::f6
			: code == SDL_SCANCODE_F7 ? scancodes::f7
			: code == SDL_SCANCODE_F8 ? scancodes::f8
			: code == SDL_SCANCODE_F9 ? scancodes::f9
			: code == SDL_SCANCODE_F10 ? scancodes::f10
			: code == SDL_SCANCODE_F11 ? scancodes::f11
			: code == SDL_SCANCODE_F12 ? scancodes::f12
			: code == SDL_SCANCODE_PRINTSCREEN ? scancodes::printscreen
			: code == SDL_SCANCODE_SCROLLLOCK ? scancodes::scroll_lock
			: code == SDL_SCANCODE_PAUSE ? scancodes::pause
			: code == SDL_SCANCODE_INSERT ? scancodes::insert
			: code == SDL_SCANCODE_HOME ? scancodes::home
			: code == SDL_SCANCODE_PAGEUP ? scancodes::page_up
			: code == SDL_SCANCODE_DELETE ? scancodes::del
			: code == SDL_SCANCODE_END ? scancodes::end
			: code == SDL_SCANCODE_PAGEDOWN ? scancodes::page_down
			: code == SDL_SCANCODE_RIGHT ? scancodes::right
			: code == SDL_SCANCODE_LEFT ? scancodes::left
			: code == SDL_SCANCODE_DOWN ? scancodes::down
			: code == SDL_SCANCODE_UP ? scancodes::up
			: code == SDL_SCANCODE_NUMLOCKCLEAR ? scancodes::numlock_clear
			: code == SDL_SCANCODE_KP_DIVIDE ? scancodes::kp_divide
			: code == SDL_SCANCODE_KP_MULTIPLY ? scancodes::kp_multiply
			: code == SDL_SCANCODE_KP_MINUS ? scancodes::kp_minus
			: code == SDL_SCANCODE_KP_PLUS ? scancodes::kp_plus
			: code == SDL_SCANCODE_KP_ENTER ? scancodes::kp_enter
			: code == SDL_SCANCODE_KP_1 ? scancodes::kp_1
			: code == SDL_SCANCODE_KP_2 ? scancodes::kp_2
			: code == SDL_SCANCODE_KP_3 ? scancodes::kp_3
			: code == SDL_SCANCODE_KP_4 ? scancodes::kp_4
			: code == SDL_SCANCODE_KP_5 ? scancodes::kp_5
			: code == SDL_SCANCODE_KP_6 ? scancodes::kp_6
			: code == SDL_SCANCODE_KP_7 ? scancodes::kp_7
			: code == SDL_SCANCODE_KP_8 ? scancodes::kp_8
			: code == SDL_SCANCODE_KP_9 ? scancodes::kp_9
			: code == SDL_SCANCODE_KP_0 ? scancodes::kp_0
			: code == SDL_SCANCODE_KP_PERIOD ? scancodes::kp_period
			: code == SDL_SCANCODE_NONUSBACKSLASH ? scancodes::non_usbackslash
			: code == SDL_SCANCODE_APPLICATION ? scancodes::application
			: code == SDL_SCANCODE_POWER ? scancodes::power
			: code == SDL_SCANCODE_KP_EQUALS ? scancodes::kp_equals
			: code == SDL_SCANCODE_F13 ? scancodes::f13
			: code == SDL_SCANCODE_F14 ? scancodes::f14
			: code == SDL_SCANCODE_F15 ? scancodes::f15
			: code == SDL_SCANCODE_F16 ? scancodes::f16
			: code == SDL_SCANCODE_F17 ? scancodes::f17
			: code == SDL_SCANCODE_F18 ? scancodes::f18
			: code == SDL_SCANCODE_F19 ? scancodes::f19
			: code == SDL_SCANCODE_F20 ? scancodes::f20
			: code == SDL_SCANCODE_F21 ? scancodes::f21
			: code == SDL_SCANCODE_F22 ? scancodes::f22
			: code == SDL_SCANCODE_F23 ? scancodes::f23
			: code == SDL_SCANCODE_F24 ? scancodes::f24
			: code == SDL_SCANCODE_EXECUTE ? scancodes::execute
			: code == SDL_SCANCODE_HELP ? scancodes::help
			: code == SDL_SCANCODE_MENU ? scancodes::menu
			: code == SDL_SCANCODE_SELECT ? scancodes::select
			: code == SDL_SCANCODE_STOP ? scancodes::stop
			: code == SDL_SCANCODE_AGAIN ? scancodes::again
			: code == SDL_SCANCODE_UNDO ? scancodes::undo
			: code == SDL_SCANCODE_CUT ? scancodes::cut
			: code == SDL_SCANCODE_COPY ? scancodes::copy
			: code == SDL_SCANCODE_PASTE ? scancodes::paste
			: code == SDL_SCANCODE_FIND ? scancodes::find
			: code == SDL_SCANCODE_MUTE ? scancodes::mute
			: code == SDL_SCANCODE_VOLUMEUP ? scancodes::volume_up
			: code == SDL_SCANCODE_VOLUMEDOWN ? scancodes::volume_down
			: code == SDL_SCANCODE_KP_COMMA ? scancodes::kp_comma
			: code == SDL_SCANCODE_KP_EQUALSAS400 ? scancodes::kp_equalsas400
			: code == SDL_SCANCODE_INTERNATIONAL1 ? scancodes::international1
			: code == SDL_SCANCODE_INTERNATIONAL2 ? scancodes::international2
			: code == SDL_SCANCODE_INTERNATIONAL3 ? scancodes::international3
			: code == SDL_SCANCODE_INTERNATIONAL4 ? scancodes::international4
			: code == SDL_SCANCODE_INTERNATIONAL5 ? scancodes::international5
			: code == SDL_SCANCODE_INTERNATIONAL6 ? scancodes::international6
			: code == SDL_SCANCODE_INTERNATIONAL7 ? scancodes::international7
			: code == SDL_SCANCODE_INTERNATIONAL8 ? scancodes::international8
			: code == SDL_SCANCODE_INTERNATIONAL9 ? scancodes::international9
			: code == SDL_SCANCODE_LANG1 ? scancodes::lang1
			: code == SDL_SCANCODE_LANG2 ? scancodes::lang2
			: code == SDL_SCANCODE_LANG3 ? scancodes::lang3
			: code == SDL_SCANCODE_LANG4 ? scancodes::lang4
			: code == SDL_SCANCODE_LANG5 ? scancodes::lang5
			: code == SDL_SCANCODE_LANG6 ? scancodes::lang6
			: code == SDL_SCANCODE_LANG7 ? scancodes::lang7
			: code == SDL_SCANCODE_LANG8 ? scancodes::lang8
			: code == SDL_SCANCODE_LANG9 ? scancodes::lang9
			: code == SDL_SCANCODE_ALTERASE ? scancodes::alterase
			: code == SDL_SCANCODE_SYSREQ ? scancodes::sysreq
			: code == SDL_SCANCODE_CANCEL ? scancodes::cancel
			: code == SDL_SCANCODE_CLEAR ? scancodes::clear
			: code == SDL_SCANCODE_PRIOR ? scancodes::prior
			: code == SDL_SCANCODE_RETURN2 ? scancodes::return2
			: code == SDL_SCANCODE_SEPARATOR ? scancodes::separator
			: code == SDL_SCANCODE_OUT ? scancodes::out
			: code == SDL_SCANCODE_OPER ? scancodes::oper
			: code == SDL_SCANCODE_CLEARAGAIN ? scancodes::clear_again
			: code == SDL_SCANCODE_CRSEL ? scancodes::crsel
			: code == SDL_SCANCODE_EXSEL ? scancodes::exsel
			: code == SDL_SCANCODE_KP_00 ? scancodes::kp_00
			: code == SDL_SCANCODE_KP_000 ? scancodes::kp_000
			: code == SDL_SCANCODE_THOUSANDSSEPARATOR ? scancodes::thousands_separator
			: code == SDL_SCANCODE_DECIMALSEPARATOR ? scancodes::decimal_separator
			: code == SDL_SCANCODE_CURRENCYUNIT ? scancodes::currency_unit
			: code == SDL_SCANCODE_CURRENCYSUBUNIT ? scancodes::currency_subunit
			: code == SDL_SCANCODE_KP_LEFTPAREN ? scancodes::kp_left_paren
			: code == SDL_SCANCODE_KP_RIGHTPAREN ? scancodes::kp_right_paren
			: code == SDL_SCANCODE_KP_LEFTBRACE ? scancodes::kp_left_brace
			: code == SDL_SCANCODE_KP_RIGHTBRACE ? scancodes::kp_right_brace
			: code == SDL_SCANCODE_KP_TAB ? scancodes::kp_tab
			: code == SDL_SCANCODE_KP_BACKSPACE ? scancodes::kp_backspace
			: code == SDL_SCANCODE_KP_A ? scancodes::kp_a
			: code == SDL_SCANCODE_KP_B ? scancodes::kp_b
			: code == SDL_SCANCODE_KP_C ? scancodes::kp_c
			: code == SDL_SCANCODE_KP_D ? scancodes::kp_d
			: code == SDL_SCANCODE_KP_E ? scancodes::kp_e
			: code == SDL_SCANCODE_KP_F ? scancodes::kp_f
			: code == SDL_SCANCODE_KP_XOR ? scancodes::kp_xor
			: code == SDL_SCANCODE_KP_POWER ? scancodes::kp_power
			: code == SDL_SCANCODE_KP_PERCENT ? scancodes::kp_percent
			: code == SDL_SCANCODE_KP_LESS ? scancodes::kp_less
			: code == SDL_SCANCODE_KP_GREATER ? scancodes::kp_greater
			: code == SDL_SCANCODE_KP_AMPERSAND ? scancodes::kp_ampersand
			: code == SDL_SCANCODE_KP_DBLAMPERSAND ? scancodes::kp_dblampersand
			: code == SDL_SCANCODE_KP_VERTICALBAR ? scancodes::kp_verticalbar
			: code == SDL_SCANCODE_KP_DBLVERTICALBAR ? scancodes::kp_dblverticalbar
			: code == SDL_SCANCODE_KP_COLON ? scancodes::kp_colon
			: code == SDL_SCANCODE_KP_HASH ? scancodes::kp_hash
			: code == SDL_SCANCODE_KP_SPACE ? scancodes::kp_space
			: code == SDL_SCANCODE_KP_AT ? scancodes::kp_at
			: code == SDL_SCANCODE_KP_EXCLAM ? scancodes::kp_exclam
			: code == SDL_SCANCODE_KP_MEMSTORE ? scancodes::kp_mem_store
			: code == SDL_SCANCODE_KP_MEMRECALL ? scancodes::kp_mem_recall
			: code == SDL_SCANCODE_KP_MEMCLEAR ? scancodes::kp_mem_clear
			: code == SDL_SCANCODE_KP_MEMADD ? scancodes::kp_mem_add
			: code == SDL_SCANCODE_KP_MEMSUBTRACT ? scancodes::kp_mem_subtract
			: code == SDL_SCANCODE_KP_MEMMULTIPLY ? scancodes::kp_mem_multiply
			: code == SDL_SCANCODE_KP_MEMDIVIDE ? scancodes::kp_mem_divide
			: code == SDL_SCANCODE_KP_PLUSMINUS ? scancodes::kp_plus_minus
			: code == SDL_SCANCODE_KP_CLEAR ? scancodes::kp_clear
			: code == SDL_SCANCODE_KP_CLEARENTRY ? scancodes::kp_clear_entry
			: code == SDL_SCANCODE_KP_BINARY ? scancodes::kp_binary
			: code == SDL_SCANCODE_KP_OCTAL ? scancodes::kp_octal
			: code == SDL_SCANCODE_KP_DECIMAL ? scancodes::kp_decimal
			: code == SDL_SCANCODE_KP_HEXADECIMAL ? scancodes::kp_hexadecimal
			: code == SDL_SCANCODE_LCTRL ? scancodes::left_ctrl
			: code == SDL_SCANCODE_LSHIFT ? scancodes::left_shift
			: code == SDL_SCANCODE_LALT ? scancodes::left_alt
			: code == SDL_SCANCODE_LGUI ? scancodes::left_gui
			: code == SDL_SCANCODE_RCTRL ? scancodes::right_ctrl
			: code == SDL_SCANCODE_RSHIFT ? scancodes::right_shift
			: code == SDL_SCANCODE_RALT ? scancodes::right_alt
			: code == SDL_SCANCODE_RGUI ? scancodes::right_gui
			: code == SDL_SCANCODE_MODE ? scancodes::mode
			: code == SDL_SCANCODE_AUDIONEXT ? scancodes::audio_next
			: code == SDL_SCANCODE_AUDIOPREV ? scancodes::audio_prev
			: code == SDL_SCANCODE_AUDIOSTOP ? scancodes::audio_stop
			: code == SDL_SCANCODE_AUDIOPLAY ? scancodes::audio_play
			: code == SDL_SCANCODE_AUDIOMUTE ? scancodes::audio_mute
			: code == SDL_SCANCODE_MEDIASELECT ? scancodes::media_select
			: code == SDL_SCANCODE_WWW ? scancodes::www
			: code == SDL_SCANCODE_MAIL ? scancodes::mail
			: code == SDL_SCANCODE_CALCULATOR ? scancodes::calculator
			: code == SDL_SCANCODE_COMPUTER ? scancodes::computer
			: code == SDL_SCANCODE_AC_SEARCH ? scancodes::ac_search
			: code == SDL_SCANCODE_AC_HOME ? scancodes::ac_home
			: code == SDL_SCANCODE_AC_BACK ? scancodes::ac_back
			: code == SDL_SCANCODE_AC_FORWARD ? scancodes::ac_forward
			: code == SDL_SCANCODE_AC_STOP ? scancodes::ac_stop
			: code == SDL_SCANCODE_AC_REFRESH ? scancodes::ac_refresh
			: code == SDL_SCANCODE_AC_BOOKMARKS ? scancodes::ac_bookmarks
			: code == SDL_SCANCODE_BRIGHTNESSDOWN ? scancodes::brightness_down
			: code == SDL_SCANCODE_BRIGHTNESSUP ? scancodes::brightness_up
			: code == SDL_SCANCODE_DISPLAYSWITCH ? scancodes::display_switch
			: code == SDL_SCANCODE_KBDILLUMTOGGLE ? scancodes::kbd_illum_toggle
			: code == SDL_SCANCODE_KBDILLUMDOWN ? scancodes::kbd_illum_down
			: code == SDL_SCANCODE_KBDILLUMUP ? scancodes::kbd_illum_up
			: code == SDL_SCANCODE_EJECT ? scancodes::eject
			: code == SDL_SCANCODE_SLEEP ? scancodes::sleep
			: code == SDL_SCANCODE_APP1 ? scancodes::app1
			: code == SDL_SCANCODE_APP2 ? scancodes::app2
			: code == SDL_SCANCODE_AUDIOREWIND ? scancodes::audio_rewind
			: code == SDL_SCANCODE_AUDIOFASTFORWARD ? scancodes::audio_fastforward
			: scancodes::unknown;
	}

	constexpr SDL_Scancode to_sdl(scancodes code) noexcept
	{
		return code == scancodes::a ? SDL_SCANCODE_A
			: code == scancodes::b ? SDL_SCANCODE_B
			: code == scancodes::c ? SDL_SCANCODE_C
			: code == scancodes::d ? SDL_SCANCODE_D
			: code == scancodes::e ? SDL_SCANCODE_E
			: code == scancodes::f ? SDL_SCANCODE_F
			: code == scancodes::g ? SDL_SCANCODE_G
			: code == scancodes::h ? SDL_SCANCODE_H
			: code == scancodes::i ? SDL_SCANCODE_I
			: code == scancodes::j ? SDL_SCANCODE_J
			: code == scancodes::k ? SDL_SCANCODE_K
			: code == scancodes::l ? SDL_SCANCODE_L
			: code == scancodes::m ? SDL_SCANCODE_M
			: code == scancodes::n ? SDL_SCANCODE_N
			: code == scancodes::o ? SDL_SCANCODE_O
			: code == scancodes::p ? SDL_SCANCODE_P
			: code == scancodes::q ? SDL_SCANCODE_Q
			: code == scancodes::r ? SDL_SCANCODE_R
			: code == scancodes::s ? SDL_SCANCODE_S
			: code == scancodes::t ? SDL_SCANCODE_T
			: code == scancodes::u ? SDL_SCANCODE_U
			: code == scancodes::v ? SDL_SCANCODE_V
			: code == scancodes::w ? SDL_SCANCODE_W
			: code == scancodes::x ? SDL_SCANCODE_X
			: code == scancodes::y ? SDL_SCANCODE_Y
			: code == scancodes::z ? SDL_SCANCODE_Z
			: code == scancodes::num_1 ? SDL_SCANCODE_1
			: code == scancodes::num_2 ? SDL_SCANCODE_2
			: code == scancodes::num_3 ? SDL_SCANCODE_3
			: code == scancodes::num_4 ? SDL_SCANCODE_4
			: code == scancodes::num_5 ? SDL_SCANCODE_5
			: code == scancodes::num_6 ? SDL_SCANCODE_6
			: code == scancodes::num_7 ? SDL_SCANCODE_7
			: code == scancodes::num_8 ? SDL_SCANCODE_8
			: code == scancodes::num_9 ? SDL_SCANCODE_9
			: code == scancodes::num_0 ? SDL_SCANCODE_0
			: code == scancodes::enter ? SDL_SCANCODE_RETURN
			: code == scancodes::escape ? SDL_SCANCODE_ESCAPE
			: code == scancodes::backspace ? SDL_SCANCODE_BACKSPACE
			: code == scancodes::tab ? SDL_SCANCODE_TAB
			: code == scancodes::space ? SDL_SCANCODE_SPACE
			: code == scancodes::minus ? SDL_SCANCODE_MINUS
			: code == scancodes::equals ? SDL_SCANCODE_EQUALS
			: code == scancodes::left_bracket ? SDL_SCANCODE_LEFTBRACKET
			: code == scancodes::right_bracket ? SDL_SCANCODE_RIGHTBRACKET
			: code == scancodes::backslash ? SDL_SCANCODE_BACKSLASH
			: code == scancodes::non_ushash ? SDL_SCANCODE_NONUSHASH
			: code == scancodes::semicolon ? SDL_SCANCODE_SEMICOLON
			: code == scancodes::apostrophe ? SDL_SCANCODE_APOSTROPHE
			: code == scancodes::grave ? SDL_SCANCODE_GRAVE
			: code == scancodes::comma ? SDL_SCANCODE_COMMA
			: code == scancodes::period ? SDL_SCANCODE_PERIOD
			: code == scancodes::slash ? SDL_SCANCODE_SLASH
			: code == scancodes::capslock ? SDL_SCANCODE_CAPSLOCK
			: code == scancodes::f1 ? SDL_SCANCODE_F1
			: code == scancodes::f2 ? SDL_SCANCODE_F2
			: code == scancodes::f3 ? SDL_SCANCODE_F3
			: code == scancodes::f4 ? SDL_SCANCODE_F4
			: code == scancodes::f5 ? SDL_SCANCODE_F5
			: code == scancodes::f6 ? SDL_SCANCODE_F6
			: code == scancodes::f7 ? SDL_SCANCODE_F7
			: code == scancodes::f8 ? SDL_SCANCODE_F8
			: code == scancodes::f9 ? SDL_SCANCODE_F9
			: code == scancodes::f10 ? SDL_SCANCODE_F10
			: code == scancodes::f11 ? SDL_SCANCODE_F11
			: code == scancodes::f12 ? SDL_SCANCODE_F12
			: code == scancodes::printscreen ? SDL_SCANCODE_PRINTSCREEN
			: code == scancodes::scroll_lock ? SDL_SCANCODE_SCROLLLOCK
			: code == scancodes::pause ? SDL_SCANCODE_PAUSE
			: code == scancodes::insert ? SDL_SCANCODE_INSERT
			: code == scancodes::home ? SDL_SCANCODE_HOME
			: code == scancodes::page_up ? SDL_SCANCODE_PAGEUP
			: code == scancodes::del ? SDL_SCANCODE_DELETE
			: code == scancodes::end ? SDL_SCANCODE_END
			: code == scancodes::page_down ? SDL_SCANCODE_PAGEDOWN
			: code == scancodes::right ? SDL_SCANCODE_RIGHT
			: code == scancodes::left ? SDL_SCANCODE_LEFT
			: code == scancodes::down ? SDL_SCANCODE_DOWN
			: code == scancodes::up ? SDL_SCANCODE_UP
			: code == scancodes::numlock_clear ? SDL_SCANCODE_NUMLOCKCLEAR
			: code == scancodes::kp_divide ? SDL_SCANCODE_KP_DIVIDE
			: code == scancodes::kp_multiply ? SDL_SCANCODE_KP_MULTIPLY
			: code == scancodes::kp_minus ? SDL_SCANCODE_KP_MINUS
			: code == scancodes::kp_plus ? SDL_SCANCODE_KP_PLUS
			: code == scancodes::kp_enter ? SDL_SCANCODE_KP_ENTER
			: code == scancodes::kp_1 ? SDL_SCANCODE_KP_1
			: code == scancodes::kp_2 ? SDL_SCANCODE_KP_2
			: code == scancodes::kp_3 ? SDL_SCANCODE_KP_3
			: code == scancodes::kp_4 ? SDL_SCANCODE_KP_4
			: code == scancodes::kp_5 ? SDL_SCANCODE_KP_5
			: code == scancodes::kp_6 ? SDL_SCANCODE_KP_6
			: code == scancodes::kp_7 ? SDL_SCANCODE_KP_7
			: code == scancodes::kp_8 ? SDL_SCANCODE_KP_8
			: code == scancodes::kp_9 ? SDL_SCANCODE_KP_9
			: code == scancodes::kp_0 ? SDL_SCANCODE_KP_0
			: code == scancodes::kp_period ? SDL_SCANCODE_KP_PERIOD
			: code == scancodes::non_usbackslash ? SDL_SCANCODE_NONUSBACKSLASH
			: code == scancodes::application ? SDL_SCANCODE_APPLICATION
			: code == scancodes::power ? SDL_SCANCODE_POWER
			: code == scancodes::kp_equals ? SDL_SCANCODE_KP_EQUALS
			: code == scancodes::f13 ? SDL_SCANCODE_F13
			: code == scancodes::f14 ? SDL_SCANCODE_F14
			: code == scancodes::f15 ? SDL_SCANCODE_F15
			: code == scancodes::f16 ? SDL_SCANCODE_F16
			: code == scancodes::f17 ? SDL_SCANCODE_F17
			: code == scancodes::f18 ? SDL_SCANCODE_F18
			: code == scancodes::f19 ? SDL_SCANCODE_F19
			: code == scancodes::f20 ? SDL_SCANCODE_F20
			: code == scancodes::f21 ? SDL_SCANCODE_F21
			: code == scancodes::f22 ? SDL_SCANCODE_F22
			: code == scancodes::f23 ? SDL_SCANCODE_F23
			: code == scancodes::f24 ? SDL_SCANCODE_F24
			: code == scancodes::execute ? SDL_SCANCODE_EXECUTE
			: code == scancodes::help ? SDL_SCANCODE_HELP
			: code == scancodes::menu ? SDL_SCANCODE_MENU
			: code == scancodes::select ? SDL_SCANCODE_SELECT
			: code == scancodes::stop ? SDL_SCANCODE_STOP
			: code == scancodes::again ? SDL_SCANCODE_AGAIN
			: code == scancodes::undo ? SDL_SCANCODE_UNDO
			: code == scancodes::cut ? SDL_SCANCODE_CUT
			: code == scancodes::copy ? SDL_SCANCODE_COPY
			: code == scancodes::paste ? SDL_SCANCODE_PASTE
			: code == scancodes::find ? SDL_SCANCODE_FIND
			: code == scancodes::mute ? SDL_SCANCODE_MUTE
			: code == scancodes::volume_up ? SDL_SCANCODE_VOLUMEUP
			: code == scancodes::volume_down ? SDL_SCANCODE_VOLUMEDOWN
			: code == scancodes::kp_comma ? SDL_SCANCODE_KP_COMMA
			: code == scancodes::kp_equalsas400 ? SDL_SCANCODE_KP_EQUALSAS400
			: code == scancodes::international1 ? SDL_SCANCODE_INTERNATIONAL1
			: code == scancodes::international2 ? SDL_SCANCODE_INTERNATIONAL2
			: code == scancodes::international3 ? SDL_SCANCODE_INTERNATIONAL3
			: code == scancodes::international4 ? SDL_SCANCODE_INTERNATIONAL4
			: code == scancodes::international5 ? SDL_SCANCODE_INTERNATIONAL5
			: code == scancodes::international6 ? SDL_SCANCODE_INTERNATIONAL6
			: code == scancodes::international7 ? SDL_SCANCODE_INTERNATIONAL7
			: code == scancodes::international8 ? SDL_SCANCODE_INTERNATIONAL8
			: code == scancodes::international9 ? SDL_SCANCODE_INTERNATIONAL9
			: code == scancodes::lang1 ? SDL_SCANCODE_LANG1
			: code == scancodes::lang2 ? SDL_SCANCODE_LANG2
			: code == scancodes::lang3 ? SDL_SCANCODE_LANG3
			: code == scancodes::lang4 ? SDL_SCANCODE_LANG4
			: code == scancodes::lang5 ? SDL_SCANCODE_LANG5
			: code == scancodes::lang6 ? SDL_SCANCODE_LANG6
			: code == scancodes::lang7 ? SDL_SCANCODE_LANG7
			: code == scancodes::lang8 ? SDL_SCANCODE_LANG8
			: code == scancodes::lang9 ? SDL_SCANCODE_LANG9
			: code == scancodes::alterase ? SDL_SCANCODE_ALTERASE
			: code == scancodes::sysreq ? SDL_SCANCODE_SYSREQ
			: code == scancodes::cancel ? SDL_SCANCODE_CANCEL
			: code == scancodes::clear ? SDL_SCANCODE_CLEAR
			: code == scancodes::prior ? SDL_SCANCODE_PRIOR
			: code == scancodes::return2 ? SDL_SCANCODE_RETURN2
			: code == scancodes::separator ? SDL_SCANCODE_SEPARATOR
			: code == scancodes::out ? SDL_SCANCODE_OUT
			: code == scancodes::oper ? SDL_SCANCODE_OPER
			: code == scancodes::clear_again ? SDL_SCANCODE_CLEARAGAIN
			: code == scancodes::crsel ? SDL_SCANCODE_CRSEL
			: code == scancodes::exsel ? SDL_SCANCODE_EXSEL
			: code == scancodes::kp_00 ? SDL_SCANCODE_KP_00
			: code == scancodes::kp_000 ? SDL_SCANCODE_KP_000
			: code == scancodes::thousands_separator ? SDL_SCANCODE_THOUSANDSSEPARATOR
			: code == scancodes::decimal_separator ? SDL_SCANCODE_DECIMALSEPARATOR
			: code == scancodes::currency_unit ? SDL_SCANCODE_CURRENCYUNIT
			: code == scancodes::currency_subunit ? SDL_SCANCODE_CURRENCYSUBUNIT
			: code == scancodes::kp_left_paren ? SDL_SCANCODE_KP_LEFTPAREN
			: code == scancodes::kp_right_paren ? SDL_SCANCODE_KP_RIGHTPAREN
			: code == scancodes::kp_left_brace ? SDL_SCANCODE_KP_LEFTBRACE
			: code == scancodes::kp_right_brace ? SDL_SCANCODE_KP_RIGHTBRACE
			: code == scancodes::kp_tab ? SDL_SCANCODE_KP_TAB
			: code == scancodes::kp_backspace ? SDL_SCANCODE_KP_BACKSPACE
			: code == scancodes::kp_a ? SDL_SCANCODE_KP_A
			: code == scancodes::kp_b ? SDL_SCANCODE_KP_B
			: code == scancodes::kp_c ? SDL_SCANCODE_KP_C
			: code == scancodes::kp_d ? SDL_SCANCODE_KP_D
			: code == scancodes::kp_e ? SDL_SCANCODE_KP_E
			: code == scancodes::kp_f ? SDL_SCANCODE_KP_F
			: code == scancodes::kp_xor ? SDL_SCANCODE_KP_XOR
			: code == scancodes::kp_power ? SDL_SCANCODE_KP_POWER
			: code == scancodes::kp_percent ? SDL_SCANCODE_KP_PERCENT
			: code == scancodes::kp_less ? SDL_SCANCODE_KP_LESS
			: code == scancodes::kp_greater ? SDL_SCANCODE_KP_GREATER
			: code == scancodes::kp_ampersand ? SDL_SCANCODE_KP_AMPERSAND
			: code == scancodes::kp_dblampersand ? SDL_SCANCODE_KP_DBLAMPERSAND
			: code == scancodes::kp_verticalbar ? SDL_SCANCODE_KP_VERTICALBAR
			: code == scancodes::kp_dblverticalbar ? SDL_SCANCODE_KP_DBLVERTICALBAR
			: code == scancodes::kp_colon ? SDL_SCANCODE_KP_COLON
			: code == scancodes::kp_hash ? SDL_SCANCODE_KP_HASH
			: code == scancodes::kp_space ? SDL_SCANCODE_KP_SPACE
			: code == scancodes::kp_at ? SDL_SCANCODE_KP_AT
			: code == scancodes::kp_exclam ? SDL_SCANCODE_KP_EXCLAM
			: code == scancodes::kp_mem_store ? SDL_SCANCODE_KP_MEMSTORE
			: code == scancodes::kp_mem_recall ? SDL_SCANCODE_KP_MEMRECALL
			: code == scancodes::kp_mem_clear ? SDL_SCANCODE_KP_MEMCLEAR
			: code == scancodes::kp_mem_add ? SDL_SCANCODE_KP_MEMADD
			: code == scancodes::kp_mem_subtract ? SDL_SCANCODE_KP_MEMSUBTRACT
			: code == scancodes::kp_mem_multiply ? SDL_SCANCODE_KP_MEMMULTIPLY
			: code == scancodes::kp_mem_divide ? SDL_SCANCODE_KP_MEMDIVIDE
			: code == scancodes::kp_plus_minus ? SDL_SCANCODE_KP_PLUSMINUS
			: code == scancodes::kp_clear ? SDL_SCANCODE_KP_CLEAR
			: code == scancodes::kp_clear_entry ? SDL_SCANCODE_KP_CLEARENTRY
			: code == scancodes::kp_binary ? SDL_SCANCODE_KP_BINARY
			: code == scancodes::kp_octal ? SDL_SCANCODE_KP_OCTAL
			: code == scancodes::kp_decimal ? SDL_SCANCODE_KP_DECIMAL
			: code == scancodes::kp_hexadecimal ? SDL_SCANCODE_KP_HEXADECIMAL
			: code == scancodes::left_ctrl ? SDL_SCANCODE_LCTRL
			: code == scancodes::left_shift ? SDL_SCANCODE_LSHIFT
			: code == scancodes::left_alt ? SDL_SCANCODE_LALT
			: code == scancodes::left_gui ? SDL_SCANCODE_LGUI
			: code == scancodes::right_ctrl ? SDL_SCANCODE_RCTRL
			: code == scancodes::right_shift ? SDL_SCANCODE_RSHIFT
			: code == scancodes::right_alt ? SDL_SCANCODE_RALT
			: code == scancodes::right_gui ? SDL_SCANCODE_RGUI
			: code == scancodes::mode ? SDL_SCANCODE_MODE
			: code == scancodes::audio_next ? SDL_SCANCODE_AUDIONEXT
			: code == scancodes::audio_prev ? SDL_SCANCODE_AUDIOPREV
			: code == scancodes::audio_stop ? SDL_SCANCODE_AUDIOSTOP
			: code == scancodes::audio_play ? SDL_SCANCODE_AUDIOPLAY
			: code == scancodes::audio_mute ? SDL_SCANCODE_AUDIOMUTE
			: code == scancodes::media_select ? SDL_SCANCODE_MEDIASELECT
			: code == scancodes::www ? SDL_SCANCODE_WWW
			: code == scancodes::mail ? SDL_SCANCODE_MAIL
			: code == scancodes::calculator ? SDL_SCANCODE_CALCULATOR
			: code == scancodes::computer ? SDL_SCANCODE_COMPUTER
			: code == scancodes::ac_search ? SDL_SCANCODE_AC_SEARCH
			: code == scancodes::ac_home ? SDL_SCANCODE_AC_HOME
			: code == scancodes::ac_back ? SDL_SCANCODE_AC_BACK
			: code == scancodes::ac_forward ? SDL_SCANCODE_AC_FORWARD
			: code == scancodes::ac_stop ? SDL_SCANCODE_AC_STOP
			: code == scancodes::ac_refresh ? SDL_SCANCODE_AC_REFRESH
			: code == scancodes::ac_bookmarks ? SDL_SCANCODE_AC_BOOKMARKS
			: code == scancodes::brightness_down ? SDL_SCANCODE_BRIGHTNESSDOWN
			: code == scancodes::brightness_up ? SDL_SCANCODE_BRIGHTNESSUP
			: code == scancodes::display_switch ? SDL_SCANCODE_DISPLAYSWITCH
			: code == scancodes::kbd_illum_toggle ? SDL_SCANCODE_KBDILLUMTOGGLE
			: code == scancodes::kbd_illum_down ? SDL_SCANCODE_KBDILLUMDOWN
			: code == scancodes::kbd_illum_up ? SDL_SCANCODE_KBDILLUMUP
			: code == scancodes::eject ? SDL_SCANCODE_EJECT
			: code == scancodes::sleep ? SDL_SCANCODE_SLEEP
			: code == scancodes::app1 ? SDL_SCANCODE_APP1
			: code == scancodes::app2 ? SDL_SCANCODE_APP2
			: code == scancodes::audio_rewind ? SDL_SCANCODE_AUDIOREWIND
			: code == scancodes::audio_fastforward ? SDL_SCANCODE_AUDIOFASTFORWARD
			: SDL_SCANCODE_UNKNOWN;
	}
}
